import { Radio, FlaskConical, Database, FileText, Sparkles, ShieldCheck } from 'lucide-react';
import { cn } from './ui/utils';

export type DataProvenance = 'live' | 'reference' | 'imported' | 'ai-draft' | 'template-draft' | 'approved';

const PROVENANCE_CONFIG: Record<DataProvenance, {
  label: string;
  title: string;
  icon: typeof Radio;
  className: string;
}> = {
  live: {
    label: 'Live panel data',
    title: 'Aggregated from real panelist submissions in this workspace.',
    icon: Radio,
    className: 'bg-emerald-50 text-emerald-800 border-emerald-300',
  },
  reference: {
    label: '',
    title: 'Simulated research dataset for demonstration and method validation — not collected from your panel. Do not use in client deliverables.',
    icon: FlaskConical,
    className: 'bg-amber-50 text-amber-800 border-amber-300',
  },
  imported: {
    label: 'Imported instrument data',
    title: 'Loaded from a CSV instrument import (E-Tongue / GC-MS / composition).',
    icon: Database,
    className: 'bg-blue-50 text-blue-800 border-blue-300',
  },
  'ai-draft': {
    label: 'AI draft',
    title: 'Generated by AI and not yet approved. It cannot reach panelists or client deliverables until an admin approves it.',
    icon: Sparkles,
    className: 'bg-violet-50 text-violet-800 border-violet-300',
  },
  'template-draft': {
    label: 'Template draft',
    title: 'Built deterministically from the concept brief and category templates. Review and approve it before launch.',
    icon: FileText,
    className: 'bg-blue-50 text-blue-800 border-blue-300',
  },
  approved: {
    label: 'Admin approved',
    title: 'Reviewed and approved by an admin.',
    icon: ShieldCheck,
    className: 'bg-slate-100 text-slate-700 border-slate-300',
  },
};

/**
 * Standard badge marking whether a chart or metric is backed by live panel
 * responses, the built-in simulated reference dataset, or an instrument
 * import. Use everywhere a viewer could mistake demo data for real results.
 */
export function DataProvenanceBadge({ provenance, n, detail, className }: {
  provenance: DataProvenance;
  /** Number of panelists/observations behind the data, when known. */
  n?: number;
  /** Short suffix, e.g. the approver and date on an 'approved' badge. */
  detail?: string;
  className?: string;
}) {
  if (provenance === 'reference') return null;

  const config = PROVENANCE_CONFIG[provenance];
  const Icon = config.icon;
  return (
    <span
      title={config.title}
      className={cn(
        'inline-flex w-fit shrink-0 items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-semibold',
        config.className,
        className,
      )}
    >
      <Icon className="size-3" aria-hidden />
      {config.label}
      {typeof n === 'number' && <span className="font-normal opacity-80">n={n}</span>}
      {detail && <span className="font-normal opacity-80">{detail}</span>}
    </span>
  );
}
